version: '3.8'

services:
  db:
    image: mysql:8.0.34
    env_file:
      - .env
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - "./myBlog-api/resources/sql/:/docker-entrypoint-initdb.d/"
      - "mysql_data:/var/lib/mysql"

  api:
    build: ./myBlog-api
    env_file:
      - .env
    ports:
      - "${API_PORT}:8080"
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh"
    command: bash -c "/wait-for-it.sh -h db -p 3306 -t 30 -- ./mvnw spring-boot:run"
    depends_on:
      - db

  nginx:
    build: ./myBlog-frontend
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - db
      - api

volumes:
  mysql_data:
