version: '3.8'

services:
  db:
    image: mysql:8.0.34
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - "./myBlog-api/resources/sql/:/docker-entrypoint-initdb.d/"
      - "mysql_data:/var/lib/mysql"

volumes:
  mysql_data:
